/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/99uPXyBEJwF
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import {
  Card,
  CardHeader,
  CardTitle,
  CardDescription,
  CardContent,
  CardFooter,
} from "@/components/ui/card";
import validator from "validator";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";

import Select from "react-select";
import { useState } from "react";
import { useToast } from "@/hooks/use-toast";
import { Toaster } from "../ui/toaster";

export function FormJurnal() {
  const surahOption = [
    { value: "Al-Fatihah", label: "Al-Fatihah" },
    { value: "Al-Baqarah", label: "Al-Baqarah" },
    { value: "Ali Imran", label: "Ali Imran" },
    { value: "Al-Nisa", label: "Al-Nisa" },
    { value: "Al-Maidah", label: "Al-Maidah" },
    { value: "Al-An'am", label: "Al-An'am" },
    { value: "Al-A'raf", label: "Al-A'raf" },
    { value: "Al-Anfal", label: "Al-Anfal" },
    { value: "At-Taubah", label: "At-Taubah" },
    { value: "Yunus", label: "Yunus" },
    { value: "Hud", label: "Hud" },
    { value: "Yusuf", label: "Yusuf" },
    { value: "Ar-Ra'd", label: "Ar-Ra'd" },
    { value: "Ibrahim", label: "Ibrahim" },
    { value: "Al-Hijr", label: "Al-Hijr" },
    { value: "An-Nahl", label: "An-Nahl" },
    { value: "Al-Isra'", label: "Al-Isra'" },
    { value: "Al-Kahf", label: "Al-Kahf" },
    { value: "Maryam", label: "Maryam" },
    { value: "Thaha", label: "Thaha" },
    { value: "Al-Anbiya", label: "Al-Anbiya" },
    { value: "Al-Hajj", label: "Al-Hajj" },
    { value: "Al-Mukminun", label: "Al-Mukminun" },
    { value: "An-Nur", label: "An-Nur" },
    { value: "Al-Furqan", label: "Al-Furqan" },
    { value: "Asy-Syu'ara", label: "Asy-Syu'ara" },
    { value: "An-Naml", label: "An-Naml" },
    { value: "Al-Qashash", label: "Al-Qashash" },
    { value: "Al-Ankabut", label: "Al-Ankabut" },
    { value: "Ar-Rum", label: "Ar-Rum" },
    { value: "Lukman", label: "Lukman" },
    { value: "As-Sajdah", label: "As-Sajdah" },
    { value: "Al-Ahzab", label: "Al-Ahzab" },
    { value: "Saba'", label: "Saba'" },
    { value: "Fathir", label: "Fathir" },
    { value: "Yasin", label: "Yasin" },
    { value: "Ash-Shaffat", label: "Ash-Shaffat" },
    { value: "Shad", label: "Shad" },
    { value: "Az-Zumar", label: "Az-Zumar" },
    { value: "Ghafir", label: "Ghafir" },
    { value: "Fusshilat", label: "Fusshilat" },
    { value: "Asy-Syura", label: "Asy-Syura" },
    { value: "Az-Zukhruf", label: "Az-Zukhruf" },
    { value: "Ad-Dukhan", label: "Ad-Dukhan" },
    { value: "Al-Jatsiyah", label: "Al-Jatsiyah" },
    { value: "Al-Ahqaf", label: "Al-Ahqaf" },
    { value: "Muhammad", label: "Muhammad" },
    { value: "Al-Fath", label: "Al-Fath" },
    { value: "Al-Hujurat", label: "Al-Hujurat" },
    { value: "Qaf", label: "Qaf" },
    { value: "Adz-Dzariyat", label: "Adz-Dzariyat" },
    { value: "Ath-Thur", label: "Ath-Thur" },
    { value: "An-Najm", label: "An-Najm" },
    { value: "Al-Qamar", label: "Al-Qamar" },
    { value: "Ar-Rahman", label: "Ar-Rahman" },
    { value: "Al-Waqi'ah", label: "Al-Waqi'ah" },
    { value: "Al-Hadid", label: "Al-Hadid" },
    { value: "Al-Mujadilah", label: "Al-Mujadilah" },
    { value: "Al-Hasyr", label: "Al-Hasyr" },
    { value: "Al-Mumtahanah", label: "Al-Mumtahanah" },
    { value: "Ash-Shaff", label: "Ash-Shaff" },
    { value: "Al-Jumu'ah", label: "Al-Jumu'ah" },
    { value: "Al-Munafiqun", label: "Al-Munafiqun" },
    { value: "At-Taghabun", label: "At-Taghabun" },
    { value: "Ath-Thalaq", label: "Ath-Thalaq" },
    { value: "At-Tahrim", label: "At-Tahrim" },
    { value: "Al-Mulk", label: "Al-Mulk" },
    { value: "Al-Qalam", label: "Al-Qalam" },
    { value: "Al-Haqqah", label: "Al-Haqqah" },
    { value: "Al-Ma'arij", label: "Al-Ma'arij" },
    { value: "Nuh", label: "Nuh" },
    { value: "Al-Jin", label: "Al-Jin" },
    { value: "Al-Muzammil", label: "Al-Muzammil" },
    { value: "Al-Muddatsir", label: "Al-Muddatsir" },
    { value: "Al-Qiyamah", label: "Al-Qiyamah" },
    { value: "Al-Insan", label: "Al-Insan" },
    { value: "Al-Mursalat", label: "Al-Mursalat" },
    { value: "An-Naba", label: "An-Naba" },
    { value: "An-Nazi'at", label: "An-Nazi'at" },
    { value: "'Abasa", label: "'Abasa" },
    { value: "At-Takwir", label: "At-Takwir" },
    { value: "Al-Infithar", label: "Al-Infithar" },
    { value: "Al-Muthaffifin", label: "Al-Muthaffifin" },
    { value: "Al-Insyiqaq", label: "Al-Insyiqaq" },
    { value: "Al-Buruj", label: "Al-Buruj" },
    { value: "Ath-Thariq", label: "Ath-Thariq" },
    { value: "Al-A'la", label: "Al-A'la" },
    { value: "Al-Ghasyiyah", label: "Al-Ghasyiyah" },
    { value: "Al-Fajr", label: "Al-Fajr" },
    { value: "Al-Balad", label: "Al-Balad" },
    { value: "Asy-Syams", label: "Asy-Syams" },
    { value: "Al-Lail", label: "Al-Lail" },
    { value: "Adh-Dhuha", label: "Adh-Dhuha" },
    { value: "Al-Insyirah", label: "Al-Insyirah" },
    { value: "At-Tin", label: "At-Tin" },
    { value: "Al-'Alaq", label: "Al-'Alaq" },
    { value: "Al-Qadr", label: "Al-Qadr" },
    { value: "Al-Bayyinah", label: "Al-Bayyinah" },
    { value: "Az-Zalzalah", label: "Az-Zalzalah" },
    { value: "Al-'Adiyat", label: "Al-'Adiyat" },
    { value: "Al-Qari'ah", label: "Al-Qari'ah" },
    { value: "At-Takatsur", label: "At-Takatsur" },
    { value: "Al-'Ashr", label: "Al-'Ashr" },
    { value: "Al-Humazah", label: "Al-Humazah" },
    { value: "Al-Fil", label: "Al-Fil" },
    { value: "Quraisy", label: "Quraisy" },
    { value: "Al-Ma'un", label: "Al-Ma'un" },
    { value: "Al-Kautsar", label: "Al-Kautsar" },
    { value: "Al-Kafirun", label: "Al-Kafirun" },
    { value: "An-Nashr", label: "An-Nashr" },
    { value: "Al-Masad", label: "Al-Masad" },
    { value: "Al-Ikhlash", label: "Al-Ikhlash" },
    { value: "Al-Falaq", label: "Al-Falaq" },
    { value: "An-Nas", label: "An-Nas" },
  ];
  const [surah, setSurah] = useState("");
  const [ayat, setAyat] = useState("");
  const [catatan, setCatatan] = useState("");

  const { toast } = useToast();

  const handleSubmit = (e: any) => {
    e.preventDefault();

    if (
      validator.isEmpty(surah, { ignore_whitespace: true }) ||
      validator.isEmpty(ayat, { ignore_whitespace: true })
    ) {
      toast({
        variant: "destructive",
        title: "SURAH ATAU AYAT TIDAK BOLEH KOSONG",
        className: "bg-red-200",
      });
    } else {
      fetch("api/jurnal", {
        method: "POST",
        body: JSON.stringify({
          surah,
          ayat,
          catatan,
        }),
      })
        .then((response) => response.json())
        .then((data) => {
          // setAyat("");
          // setSurah("");
          // setCatatan("");
          toast({
            title: "BEHRHASIL MENAMBAHKAN JURNAL",
            description: "Semoga istiqomah :)",
            className: "bg-white",
          });
        })
        .catch((err) => {
          toast({
            variant: "destructive",
            title: "ADA KESALAHAN, COBA LAGI",
            description: "Jika terus terjadi, hubungi admin",
            className: "bg-red-200",
          });
        });
    }
  };

  return (
    <Card className="w-full max-w-md">
      <Toaster />
      <CardHeader>
        <CardTitle>Jurnal Tahfidz Al-Quran</CardTitle>
        <CardDescription>Catat kemajuan tahfizmu di sini.</CardDescription>
      </CardHeader>
      <form onSubmit={handleSubmit}>
        <CardContent className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="surah">Nama Surah</Label>
            <Select
              id="surah"
              options={surahOption}
              onChange={(e: any) => {
                setSurah(e.value);
              }}
              placeholder="Masukkan nama surah"
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor="ayat">Nomor Ayat</Label>
            <Input
              id="ayat"
              type="text"
              placeholder="Contoh 1-10"
              value={ayat}
              onChange={(e) => setAyat(e.target.value)}
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor="catatan">Catatan</Label>
            <Textarea
              value={catatan}
              id="catatan"
              placeholder="Tulis catatan atau refleksi kamu di sini"
              onChange={(e) => setCatatan(e.target.value)}
            />
          </div>
        </CardContent>
        <CardFooter className="flex justify-end">
          <Button type="submit" className="bg-slate-900 text-white">
            Simpan
          </Button>
        </CardFooter>
      </form>
    </Card>
  );
}
