/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Cye8EaqVmRq
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Select from "react-select";
import {
  Card,
  CardHeader,
  CardTitle,
  CardDescription,
  CardContent,
  CardFooter,
} from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";

import { Button } from "@/components/ui/button";
import { useState } from "react";
import validator from "validator";

const options = [
  { value: "X PPLG 1", label: "X PPLG 1" },
  { value: "X PPLG 2", label: "X PPLG 2" },
  { value: "X AKL 1", label: "X AKL 1" },
  { value: "X AKL 2", label: "X AKL 2" },
  { value: "X AKL 3", label: "X AKL 3" },
  { value: "X AKL 4", label: "X AKL 4" },
  { value: "X DKV 1", label: "X DKV 1" },
  { value: "X DKV 2", label: "X DKV 2" },
  { value: "X PMS 1", label: "X PMS 1" },
  { value: "X PMS 2", label: "X PMS 2" },
  { value: "X PMS 3", label: "X PMS 3" },
  { value: "X MPLB 1", label: "X MPLB 1" },
  { value: "X MPLB 2", label: "X MPLB 2" },

  { value: "XI PPLG 1", label: "XI PPLG 1" },
  { value: "XI PPLG 2", label: "XI PPLG 2" },
  { value: "XI AKL 1", label: "XI AKL 1" },
  { value: "XI AKL 2", label: "XI AKL 2" },
  { value: "XI AKL 3", label: "XI AKL 3" },
  { value: "XI AKL 4", label: "XI AKL 4" },
  { value: "XI DKV 1", label: "XI DKV 1" },
  { value: "XI DKV 2", label: "XI DKV 2" },
  { value: "XI PMS 1", label: "XI PMS 1" },
  { value: "XI PMS 2", label: "XI PMS 2" },
  { value: "XI PMS 3", label: "XI PMS 3" },
  { value: "XI MPLB 1", label: "XI MPLB 1" },
  { value: "XI MPLB 2", label: "XI MPLB 2" },

  { value: "XII PPLG 1", label: "XII PPLG 1" },
  { value: "XII PPLG 2", label: "XII PPLG 2" },
  { value: "XII AKL 1", label: "XII AKL 1" },
  { value: "XII AKL 2", label: "XII AKL 2" },
  { value: "XII AKL 3", label: "XII AKL 3" },
  { value: "XII AKL 4", label: "XII AKL 4" },
  { value: "XII DKV 1", label: "XII DKV 1" },
  { value: "XII DKV 2", label: "XII DKV 2" },
  { value: "XII PMS 1", label: "XII PMS 1" },
  { value: "XII PMS 2", label: "XII PMS 2" },
  { value: "XII PMS 3", label: "XII PMS 3" },
  { value: "XII MPLB 1", label: "XII MPLB 1" },
  { value: "XII MPLB 2", label: "XII MPLB 2" },
];

export function FormDetail({ nama, nis }: { nama: string; nis: string }) {
  const [valueNis, setValueNis] = useState<string>();
  const [namaLengkap, setNamaLengkap] = useState<string>(nama);
  const [valueKelas, setValueKelas] = useState<string>();
  const [whatsapp, setWhatsapp] = useState<string>();

  const handleSubmit = (e: any) => {
    e.preventDefault();

    fetch("api/detail", {
      method: "POST",
      body: JSON.stringify({
        nama_lengkap: namaLengkap,
        nis: valueNis,
        kelas: valueKelas,
        whatsapp: whatsapp,
      }),
    })
      .then((response) => response.json())
      .then((data) => {
        location.href = "/";
      });
  };

  return (
    <Card className="w-full max-w-md mx-auto">
      <CardHeader>
        <CardTitle>ISI IDENTITAS</CardTitle>
        <CardDescription>
          Lengkapi data diri Anda dengan mengisi formulir di bawah ini.
        </CardDescription>
      </CardHeader>
      <form onSubmit={handleSubmit}>
        <CardContent className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="nis">NIS</Label>
            <Input
              required
              id="nis"
              type="number"
              placeholder="Masukkan NIS Anda"
              value={valueNis}
              onChange={(e) => {
                setValueNis(e.target.value);
              }}
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor="name">Nama Lengkap</Label>
            <Input
              required
              id="name"
              placeholder="Masukkan nama Anda"
              value={namaLengkap}
              onChange={(e) => {
                setNamaLengkap(e.target.value);
              }}
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor="name">NOMOR WHATSAPP</Label>
            <Input
              required
              id="whatsapp"
              placeholder="Masukkan Nomor Whatsapp"
              onChange={(e) => {
                setWhatsapp(e.target.value);
              }}
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor="class">Kelas</Label>
            <Select
              required
              options={options}
              onChange={(e) => {
                setValueKelas(e?.value);
              }}
            />
          </div>
        </CardContent>
        <CardFooter>
          <Button type="submit" className="w-full">
            Simpan
          </Button>
        </CardFooter>
      </form>
    </Card>
  );
}
